---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mywebtom
  name: mywebtom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebtom
  template:
    metadata:
      labels:
        app: mywebtom
    spec:
      containers:
      - image: mywebtom
        imagePullPolicy: Never
        name: mywebtom

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mywebtom
  name: mywebtom
spec:
  ports:
  - nodePort: 32225
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mywebtom
  type: NodePort
